version: '3.8'

services:
  mongo:
    image: mongo:latest 
    container_name: mongo-db 
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest 
    container_name: mongo-express-ui
    ports:
      - "8081:8081" 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_SERVER: mongo 
    depends_on:
      - mongo

volumes:
  mongo-data: